language: node_js
node_js:
  - "10"
before_script:
  - npm i now -g
script: 
  - (cd slides && npm i && npm run build)
  - (cd demo && npm i && npm t -- --coverage && npm run build)
  - (mkdir web && cp -a slides/dist/. web)
deploy:
  provider: script
  script: now ./web --no-clipboard --token=$NOW_TOKEN --public
  skip_cleanup: true
  on:
    branch: master